# Set strict to true to turn warnings into errors to catch warnings within CI.
strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
theme:
  name: material
  # By default, fonts are pulled from Google on the Internet. To support offline usage, this is
  # disabled.
  font: false
  palette:
    scheme: slate
    primary: green
    accent: yellow
  icon:
    logo: material/calendar-expand-horizontal
    # GitHub specific.
    repo: fontawesome/brands/github
  favicon: static/calendar-expand-horizontal.svg  # TODO
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - md_in_html
extra_css:
  - static/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/niccokunzmann/python-royal-mail-click-and-drop-api
plugins:
  - search
  - offline:
      enabled: !ENV [MKDOCS_MATERIAL_OFFLINE, false]
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
  # Autodoc configuration.
  # https://github.com/tlambert03/mkdocs-api-autonav#configuration
  # - api-autonav:
  #     modules: ["src/ical2jcal"]
  # This plugin is used to validate URLs (including anchors).
  - htmlproofer:
      # This is not enabled by default because this requires network I/O, so it is inherently not
      # exactly reproducible. For larger projects, this can also slow local build times.
      validate_external_urls: !ENV [HTMLPROOFER_VALIDATE_EXTERNAL_URLS, false]
      raise_error: True
watch:
  # Watch src/ directory to reload on changes to docstrings for mkdocstrings plugin.
  - docs
  - examples
  - click_and_drop_api
site_name: python-royal-mail-click-and-drop-api
copyright: Copyright &copy; 2018-2026 John Hagen; 2026 Nicco Kunzmann
# GitHub Specific Configuration.
repo_name: python-royal-mail-click-and-drop-api
repo_url: https://github.com/niccokunzmann/python-royal-mail-click-and-drop-api
edit_uri: edit/main/docs/
nav:
  - index.md
  - maintenance.md
  - API:
    - api.md
    - AddressRequest.md
    - BillingDetailsRequest.md
    - CreateOrderErrorResponse.md
    - CreateOrderLabelErrorResponse.md
    - CreateOrderRequest.md
    - CreateOrderResponse.md
    - CreateOrdersRequest.md
    - CreateOrdersResponse.md
    - CreatePackagesResponse.md
    - DeleteOrdersResource.md
    - DeletedOrderInfo.md
    - DimensionsRequest.md
    - ErrorResponse.md
    - FailedOrderResponse.md
    - GetOrderDetailsResource.md
    - GetOrderInfoResource.md
    - GetOrderLineResult.md
    - GetOrdersDetailsResponse.md
    - GetOrdersResponse.md
    - GetPostalDetailsResult.md
    - GetShippingDetailsResult.md
    - GetTagDetailsResult.md
    - GetVersionResource.md
    - Importer.md
    - LabelGenerationRequest.md
    - LabelsApi.md
    - ManifestDetailsResponse.md
    - ManifestEligibleOrdersRequest.md
    - ManifestErrorsErrorDetailsResponse.md
    - ManifestErrorsResponse.md
    - ManifestOrdersResponse.md
    - ManifestsApi.md
    - OrderErrorInfo.md
    - OrderErrorResponse.md
    - OrderFieldResponse.md
    - OrderUpdateError.md
    - OrdersApi.md
    - PostageDetailsRequest.md
    - ProductItemRequest.md
    - RecipientDetailsRequest.md
    - SenderDetailsRequest.md
    - ShipmentPackageRequest.md
    - TagRequest.md
    - UpdateOrderStatusRequest.md
    - UpdateOrderStatusResponse.md
    - UpdateOrdersStatusRequest.md
    - UpdatedOrderInfo.md
    - VersionApi.md